### PR TITLE
Catch exceptions from update thread

### LINKED ISSUE #7: Exception in callback _chain_future
Hi @Hy3n4 ,

do you have any idea what can cause this? It uses to happen few days after starting hass and I have to restart hass to get it working. I suspect the update thread to stuck on some blocking call. Can we somehow limit the update function execution time?

```
May 27 10:26:38 localhost hass[21620]: 2019-05-27 10:26:38 INFO (Thread-16) [custom_components.cometblue.climate] Update called B7:1E:5A:99:BF:21
May 27 10:26:38 localhost hass[21620]: 2019-05-27 10:26:38 INFO (Thread-16) [cometblue.device] Connecting to device "B7:1E:5A:99:BF:21"...
May 27 10:26:42 localhost hass[21620]: 2019-05-27 10:26:42 INFO (Thread-22) [cometblue.device] Unknown characteristics discovered on "B7:1E:5A:99:BF:21": ['00002a05-0000-1000-8000-00805f9b34fb', '47e9ee40-47e9-11e4-8939-164230d1df67']
May 27 10:26:48 localhost hass[21620]: 2019-05-27 10:26:48 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.living_room is taking over 10 seconds
May 27 10:27:07 localhost hass[21620]: 2019-05-27 10:27:07 ERROR (Thread-22) [cometblue.device] Value write failed for characteristic "47e9ee30-47e9-11e4-8939-164230d1df67" with error "Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."
May 27 10:27:07 localhost hass[21620]: 2019-05-27 10:27:07 DEBUG (Thread-16) [custom_components.cometblue.climate] _current.target_temp: 22.5
May 27 10:27:08 localhost hass[21620]: 2019-05-27 10:27:08 DEBUG (Thread-16) [custom_components.cometblue.climate] _current.target_temp diff: False
May 27 10:27:08 localhost hass[21620]: 2019-05-27 10:27:08 DEBUG (Thread-16) [custom_components.cometblue.climate] _current.target_temp_h diff: True
May 27 10:27:08 localhost hass[21620]: 2019-05-27 10:27:08 DEBUG (Thread-16) [custom_components.cometblue.climate] _current.target_temp_l diff: True
May 27 10:27:08 localhost hass[21620]: 2019-05-27 10:27:08 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback _chain_future.<locals>._set_state(<Future pendi...sk._wakeup()]>, <Future at 0x...StopIteration>) at /usr/lib/python3.5/asyncio/futures.py:446
May 27 10:27:08 localhost hass[21620]: Traceback (most recent call last):
May 27 10:27:08 localhost hass[21620]:   File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
May 27 10:27:08 localhost hass[21620]:     self._callback(*self._args)
May 27 10:27:08 localhost hass[21620]:   File "/usr/lib/python3.5/asyncio/futures.py", line 448, in _set_state
May 27 10:27:08 localhost hass[21620]:     _copy_future_state(other, future)
May 27 10:27:08 localhost hass[21620]:   File "/usr/lib/python3.5/asyncio/futures.py", line 424, in _copy_future_state
May 27 10:27:08 localhost hass[21620]:     dest.set_exception(exception)
May 27 10:27:08 localhost hass[21620]:   File "/usr/lib/python3.5/asyncio/futures.py", line 364, in set_exception
May 27 10:27:08 localhost hass[21620]:     raise TypeError("StopIteration interacts badly with generators "
May 27 10:27:08 localhost hass[21620]: TypeError: StopIteration interacts badly with generators and cannot be raised into a Future
May 27 10:31:31 localhost hass[21620]: 2019-05-27 10:31:31 WARNING (MainThread) [homeassistant.components.climate] Updating cometblue climate took longer than the scheduled update interval 0:05:00
May 27 10:36:32 localhost hass[21620]: 2019-05-27 10:36:32 WARNING (MainThread) [homeassistant.components.climate] Updating cometblue climate took longer than the scheduled update interval 0:05:00
May 27 10:41:33 localhost hass[21620]: 2019-05-27 10:41:33 WARNING (MainThread) [homeassistant.components.climate] Updating cometblue climate took longer than the scheduled update interval 0:05:00
May 27 10:43:51 localhost hass[21620]: 2019-05-27 10:43:51 ERROR (MainThread) [homeassistant.components.upc_connect.device_tracker] Error on 123
May 27 10:43:51 localhost hass[21620]: 2019-05-27 10:43:51 WARNING (MainThread) [homeassistant.components.upc_connect.device_tracker] Can't read device from 192.168.0.1
May 27 10:46:34 localhost hass[21620]: 2019-05-27 10:46:34 WARNING (MainThread) [homeassistant.components.climate] Updating cometblue climate took longer than the scheduled update interval 0:05:00
May 27 10:51:35 localhost hass[21620]: 2019-05-27 10:51:35 WARNING (MainThread) [homeassistant.components.climate] Updating cometblue climate took longer than the scheduled update interval 0:05:00
May 27 10:56:36 localhost hass[21620]: 2019-05-27 10:56:36 WARNING (MainThread) [homeassistant.components.climate] Updating cometblue climate took longer than the scheduled update interval 0:05:00
May 27 11:01:37 localhost hass[21620]: 2019-05-27 11:01:37 WARNING (MainThread) [homeassistant.components.climate] Updating cometblue climate took longer than the scheduled update interval 0:05:00
May 27 11:04:25 localhost hass[21620]: 2019-05-27 11:04:25 ERROR (MainThread) [homeassistant.components.upc_connect.device_tracker] Error on 123
May 27 11:04:25 localhost hass[21620]: 2019-05-27 11:04:25 WARNING (MainThread) [homeassistant.components.upc_connect.device_tracker] Can't read device from 192.168.0.1
May 27 11:06:38 localhost hass[21620]: 2019-05-27 11:06:38 WARNING (MainThread) [homeassistant.components.climate] Updating cometblue climate took longer than the scheduled update interval 0:05:00
May 27 11:11:39 localhost hass[21620]: 2019-05-27 11:11:39 INFO (Thread-11) [custom_components.cometblue.climate] Update called B7:1E:5A:99:BF:21
May 27 11:11:39 localhost hass[21620]: 2019-05-27 11:11:39 INFO (Thread-11) [cometblue.device] Connecting to device "B7:1E:5A:99:BF:21"...
May 27 11:11:39 localhost hass[21620]: 2019-05-27 11:11:39 DEBUG (Thread-11) [custom_components.cometblue.climate] _current.target_temp: 22.5
May 27 11:11:39 localhost hass[21620]: 2019-05-27 11:11:39 DEBUG (Thread-11) [custom_components.cometblue.climate] _current.target_temp diff: False
May 27 11:11:39 localhost hass[21620]: 2019-05-27 11:11:39 DEBUG (Thread-11) [custom_components.cometblue.climate] _current.target_temp_h diff: True
May 27 11:11:39 localhost hass[21620]: 2019-05-27 11:11:39 DEBUG (Thread-11) [custom_components.cometblue.climate] _current.target_temp_l diff: True
May 27 11:11:39 localhost hass[21620]: 2019-05-27 11:11:39 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback _chain_future.<locals>._set_state(<Future pendi...sk._wakeup()]>, <Future at 0x...StopIteration>) at /usr/lib/python3.5/asyncio/futures.py:446
May 27 11:11:39 localhost hass[21620]: Traceback (most recent call last):
May 27 11:11:39 localhost hass[21620]:   File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
May 27 11:11:39 localhost hass[21620]:     self._callback(*self._args)
May 27 11:11:39 localhost hass[21620]:   File "/usr/lib/python3.5/asyncio/futures.py", line 448, in _set_state
May 27 11:11:39 localhost hass[21620]:     _copy_future_state(other, future)
May 27 11:11:39 localhost hass[21620]:   File "/usr/lib/python3.5/asyncio/futures.py", line 424, in _copy_future_state
May 27 11:11:39 localhost hass[21620]:     dest.set_exception(exception)
May 27 11:11:39 localhost hass[21620]:   File "/usr/lib/python3.5/asyncio/futures.py", line 364, in set_exception
May 27 11:11:39 localhost hass[21620]:     raise TypeError("StopIteration interacts badly with generators "
May 27 11:11:39 localhost hass[21620]: TypeError: StopIteration interacts badly with generators and cannot be raised into a Future
```

### PR DESCRIPTION
**Pull request by danielkucera**
fixes #7 , still in testing

### CODE REVIEW

**Comment by danielkucera** [comment]
After a few days of testing it seems stable. What's your opinion @Hy3n4 ?

**Comment by Hy3n4** [comment]
Shouldn’t be exception logged with error instead of warning? Or there could be a counter counting connection issues and after certain amount of unsuccessful connections raise an error?
But if it’s stable I will pull the commit.
Thanks for your work.

**Comment by danielkucera** [comment]
It happens only sporadically and next try is usually successful so it works nicely for me:
```
Jun  9 08:37:19 localhost hass[32117]: 2019-06-09 08:37:19 WARNING (Thread-2) [custom_components.cometblue.climate] Update exception: Unable to connect & resolve the device
Jun  9 08:52:31 localhost hass[32117]: 2019-06-09 08:52:31 WARNING (Thread-15) [custom_components.cometblue.climate] Update exception: Unable to connect & resolve the device
Jun  9 15:28:48 localhost hass[32117]: 2019-06-09 15:28:48 WARNING (Thread-15) [custom_components.cometblue.climate] Update exception: Unable to connect & resolve the device
Jun  9 22:20:00 localhost hass[32117]: 2019-06-09 22:20:00 WARNING (Thread-20) [custom_components.cometblue.climate] Update exception: Unable to connect & resolve the device
Jun 10 02:40:24 localhost hass[32117]: 2019-06-10 02:40:24 WARNING (Thread-20) [custom_components.cometblue.climate] Update exception: Failed to write pin to device
Jun 10 05:21:26 localhost hass[32117]: 2019-06-10 05:21:26 WARNING (Thread-11) [custom_components.cometblue.climate] Update exception: Unable to connect & resolve the device
```
Wouldn't an error mean stopping the whole hass or at least the module?

**Comment by Hy3n4** [comment]
I believe that warning should happen when something went wrong, but not an error.

In my personal opinion critical should stop whole hass or the module.

But technically it does not matter.

**Pull request merged**
